-- INSERT INTO PUBLIC.TYPE_DOCUMENT (ID, NAME)
-- VALUES (1, 'Boleto'),
--        (2, 'Comprovante'),
--        (3, 'Escritura'),
--        (4, 'Certificado'),
--        (5, 'Conta');
--
-- INSERT INTO PUBLIC.DOCUMENT (ID, ID_TYPEDOCUMENT, ARQUIVO, DESCRICAO)
-- values ( 1, 3, 'teste3.txt', 'descricao teste3'),
--         ( 2, 3, 'teste3.txt', 'descricao teste3'),
--         ( 3, 2, 'teste2.txt', 'descricao teste2');